In [42]:
import xarray as xr
import numpy as np
import pandas as pd
import pyarrow as pa
from pyarrow import csv
import pyarrow.dataset as ds
import darts


In [47]:
df = pd.read_csv("https://data.ecoforecast.org/targets/terrestrial_30min/terrestrial_30min-targets.csv.gz")
df
#df = csv.read_csv("terrestrial_30min-targets.csv.gz")


time siteID       nee          le  nee_sd_intercept  \
0       2017-02-01T10:00:00Z   BART -0.573774   -0.413316          1.129216   
1       2017-02-01T10:30:00Z   BART  0.297250   -0.126562          1.129216   
2       2017-02-01T11:00:00Z   BART       NaN         NaN          1.129216   
3       2017-02-01T11:30:00Z   BART       NaN         NaN          1.129216   
4       2017-02-01T12:00:00Z   BART  0.223635   -0.033343          1.129216   
...                      ...    ...       ...         ...               ...   
900755  2022-03-23T21:30:00Z   WREF -4.627190  -44.184677          1.536223   
900756  2022-03-23T22:00:00Z   WREF -7.835847   36.646444          1.536223   
900757  2022-03-23T22:30:00Z   WREF -8.770886   92.809654          1.536223   
900758  2022-03-23T23:00:00Z   WREF -7.636024  100.056655          1.536223   
900759  2022-03-23T23:30:00Z   WREF -6.924772   45.994673          1.536223   

        nee_sd_slopeP  nee_sd_slopeN  le_sd_intercept  le_sd_slopeP  \
0            0.205268      -0.152784        10.000358      0.114693   
1            0.205268      -0.152784        10.000358      0.114693   
2            0.205268      -0.152784        10.000358      0.114693   
3            0.205268      -0.152784        10.000358      0.114693   
4            0.205268      -0.152784        10.000358      0.114693   
...               ...            ...              ...           ...   
900755       0.233519      -0.159249        15.243799      0.131272   
900756       0.233519      -0.159249        15.243799      0.131272   
900757       0.233519      -0.159249        15.243799      0.131272   
900758       0.233519      -0.159249        15.243799      0.131272   
900759       0.233519      -0.159249        15.243799      0.131272   

        le_sd_slopeN  
0          -0.964750  
1          -0.964750  
2          -0.964750  
3          -0.964750  
4          -0.964750  
...              ...  
900755     -0.446671  
900756     -0.446671  
900757     -0.446671  
900758     -0.446671  
900759     -0.446671  

[900760 rows x 10 columns]

In [61]:
subset = df[df.siteID == "BART"]
ts = darts.TimeSeries.from_dataframe(subset, time_col='time', value_cols=['nee','le'],fill_missing_dates=True, freq='30min')
ts

<TimeSeries (DataArray) (time: 90076, component: 2, sample: 1)>
array([[[-0.57377439],
        [-0.41331598]],

       [[ 0.29724968],
        [-0.12656243]],

       [[        nan],
        [        nan]],

       ...,

       [[        nan],
        [        nan]],

       [[ 0.13614967],
        [ 2.12152533]],

       [[ 0.18710615],
        [ 1.11542111]]])
Coordinates:
  * time       (time) object 1485943200000000000 ... 1648078200000000000
  * component  (component) object 'nee' 'le'
Dimensions without coordinates: sample

In [60]:
fc = xr.load_dataset("terrestrial_30min-2022-02-01-climatology.nc", engine="netcdf4")
## Cannot coerce this into a darts.TimeSeries that easily...
#fc = fc.rename_dims({'site': 'component', 'ensemble': 'sample'})
#darts.TimeSeries.from_xarray(fc)

KeyError: 0

In [17]:





np.random.seed(0)
temperature = 15 + 8 * np.random.randn(2, 2, 3) # 2 x 2 x 3
lon = [-99.83, -99.32]
lat = [[42.25, 42.21], [42.63, 42.59]]
time = pd.date_range("2014-09-06", periods=3)
reference_time = pd.Timestamp("2014-09-05")

da2 = xr.DataArray(
    data=temperature,
    dims=["variable", "site", "time"],
    coords=dict(
        lon=(["site"], lon),
        lat=(["variable", "site"], lat),
        time=time,
        reference_time=reference_time,
    ),

    attrs=dict(
        description="Ambient temperature.",
        units="degC",
    ),
)
da2

<xarray.DataArray (variable: 2, site: 2, time: 3)>
array([[[29.11241877, 18.20125767, 22.82990387],
        [32.92714559, 29.94046392,  7.18177696]],

       [[22.60070734, 13.78914233, 14.17424919],
        [18.28478802, 16.15234857, 26.63418806]]])
Coordinates:
    lon             (site) float64 -99.83 -99.32
    lat             (variable, site) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: variable, site
Attributes:
    description:  Ambient temperature.
    units:        degC

In [19]:

np.random.seed(0)
temperature = 15 + 8 * np.random.randn(2, 2, 3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
time = pd.date_range("2014-09-06", periods=3)
reference_time = pd.Timestamp("2014-09-05")

da = xr.DataArray(
    data=temperature,
    dims=["variable", "site", "time"],
    coords=dict(
        lon=(["variable", "site"], lon),
        lat=(["variable", "site"], lat),
        time=time,
        reference_time=reference_time,
    ),

    attrs=dict(
        description="Ambient temperature.",
        units="degC",
    ),
)
da

<xarray.DataArray (variable: 2, site: 2, time: 3)>
array([[[29.11241877, 18.20125767, 22.82990387],
        [32.92714559, 29.94046392,  7.18177696]],

       [[22.60070734, 13.78914233, 14.17424919],
        [18.28478802, 16.15234857, 26.63418806]]])
Coordinates:
    lon             (variable, site) float64 -99.83 -99.32 -99.79 -99.23
    lat             (variable, site) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: variable, site
Attributes:
    description:  Ambient temperature.
    units:        degC

In [8]:

da.isel(da.argmin(...))

<xarray.DataArray ()>
array(7.18177696)
Coordinates:
    lon             float64 -99.32
    lat             float64 42.21
    time            datetime64[ns] 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Attributes:
    description:  Ambient temperature.
    units:        degC